/** Quiet Courtyard data layer: credible, editorial name records ready to be replaced by an SSG data source. */
export type Gender = "boy" | "girl" | "unisex";

export type NameRecord = {
  slug: string;
  name: string;
  arabic: string;
  gender: Gender;
  meaning: string;
  meaningTags: string[];
  origin: string;
  pronunciation: string;
  letter: string;
  popularity: number;
  isUnique?: boolean;
  isQuranic?: boolean;
  description: string;
  related: string[];
};

export const names: NameRecord[] = [
  { slug: "ayaan", name: "Ayaan", arabic: "أَيَان", gender: "boy", meaning: "A gift of God; a blessing", meaningTags: ["gift", "blessing"], origin: "Arabic", pronunciation: "AY-aan", letter: "A", popularity: 10, isUnique: true, description: "Ayaan is a modern, widely loved choice with a gentle sound and an uplifting association with blessing and divine generosity.", related: ["arham", "ihsan", "rayyan"] },
  { slug: "arham", name: "Arham", arabic: "أَرْحَم", gender: "boy", meaning: "Most merciful; compassionate", meaningTags: ["mercy", "kindness"], origin: "Arabic", pronunciation: "AR-ham", letter: "A", popularity: 9, isUnique: true, description: "Arham carries a warm association with mercy and tenderness, making it a thoughtful option for families drawn to virtue-led names.", related: ["ayaan", "ihsan", "rauf"] },
  { slug: "adam", name: "Adam", arabic: "آدَم", gender: "boy", meaning: "The first man; of the earth", meaningTags: ["prophet", "earth"], origin: "Arabic", pronunciation: "AA-dam", letter: "A", popularity: 9, isQuranic: true, description: "Adam is a classic prophetic name recognised across many cultures, valued for its simplicity, dignity, and deep religious heritage.", related: ["idris", "yusuf", "ibrahim"] },
  { slug: "zayn", name: "Zayn", arabic: "زَيْن", gender: "boy", meaning: "Beauty; grace; adornment", meaningTags: ["beauty", "grace"], origin: "Arabic", pronunciation: "ZAYN", letter: "Z", popularity: 10, description: "Zayn is concise and polished, with a meaning centred on beauty and graceful character. Its sound translates easily across many languages.", related: ["rayyan", "zaid", "sami"] },
  { slug: "rayyan", name: "Rayyan", arabic: "رَيَّان", gender: "boy", meaning: "Lush; well-watered; one of the gates of Paradise", meaningTags: ["paradise", "nature"], origin: "Arabic", pronunciation: "RAY-yaan", letter: "R", popularity: 9, isQuranic: true, description: "Rayyan evokes abundance and refreshment. It is associated in Islamic tradition with a gate of Paradise for those who fast.", related: ["ayaan", "zayn", "rizwan"] },
  { slug: "ihsan", name: "Ihsan", arabic: "إِحْسَان", gender: "boy", meaning: "Excellence; kindness; doing what is beautiful", meaningTags: ["kindness", "virtue"], origin: "Arabic", pronunciation: "ih-SAHN", letter: "I", popularity: 8, isUnique: true, description: "Ihsan is a virtue name that speaks to thoughtful goodness and excellence in action. It feels refined, meaningful, and enduring.", related: ["arham", "ayaan", "sami"] },
  { slug: "yusuf", name: "Yusuf", arabic: "يُوسُف", gender: "boy", meaning: "God increases", meaningTags: ["prophet", "abundance"], origin: "Arabic", pronunciation: "YOO-suf", letter: "Y", popularity: 9, isQuranic: true, description: "Yusuf is a much-loved prophetic name, admired for its beautiful sound and the enduring Quranic story associated with Prophet Yusuf.", related: ["adam", "idris", "ibrahim"] },
  { slug: "ibrahim", name: "Ibrahim", arabic: "إِبْرَاهِيم", gender: "boy", meaning: "Father of many nations", meaningTags: ["prophet", "heritage"], origin: "Arabic", pronunciation: "ib-RAH-heem", letter: "I", popularity: 8, isQuranic: true, description: "Ibrahim is a timeless prophetic name with a strong, melodic cadence and an important place in Islamic heritage.", related: ["adam", "yusuf", "idris"] },
  { slug: "idris", name: "Idris", arabic: "إِدْرِيس", gender: "boy", meaning: "Studious; interpreter", meaningTags: ["prophet", "wisdom"], origin: "Arabic", pronunciation: "ID-riss", letter: "I", popularity: 7, isQuranic: true, description: "Idris is a compact prophetic name associated with learning and knowledge. It offers an understated alternative to more familiar choices.", related: ["yusuf", "ibrahim", "adam"] },
  { slug: "zaid", name: "Zaid", arabic: "زَيْد", gender: "boy", meaning: "Growth; abundance; increase", meaningTags: ["growth", "abundance"], origin: "Arabic", pronunciation: "ZAYD", letter: "Z", popularity: 8, description: "Zaid is a vibrant traditional name that communicates increase and growth. Its brisk sound gives it a confident contemporary feel.", related: ["zayn", "rayyan", "rizwan"] },
  { slug: "sami", name: "Sami", arabic: "سَامِي", gender: "boy", meaning: "Elevated; lofty", meaningTags: ["virtue", "strength"], origin: "Arabic", pronunciation: "SAH-mee", letter: "S", popularity: 8, description: "Sami has a light, friendly sound and a meaning connected with elevation and high standing. It works beautifully in many language settings.", related: ["zayn", "ihsan", "arham"] },
  { slug: "rizwan", name: "Rizwan", arabic: "رِضْوَان", gender: "boy", meaning: "Contentment; acceptance", meaningTags: ["peace", "paradise"], origin: "Arabic", pronunciation: "RIZ-wan", letter: "R", popularity: 7, isUnique: true, description: "Rizwan is a thoughtful name associated with contentment and divine pleasure. It brings heritage and quiet strength together.", related: ["rayyan", "zaid", "sami"] },
  { slug: "aaliyah", name: "Aaliyah", arabic: "عَالِيَة", gender: "girl", meaning: "Exalted; lofty; high-born", meaningTags: ["elevation", "grace"], origin: "Arabic", pronunciation: "ah-LEE-yah", letter: "A", popularity: 10, description: "Aaliyah has a graceful, uplifting presence. The name is admired for its elevated meaning and easy, flowing sound.", related: ["amina", "safiya", "zara"] },
  { slug: "amina", name: "Amina", arabic: "آمِنَة", gender: "girl", meaning: "Trustworthy; faithful; safe", meaningTags: ["trust", "peace"], origin: "Arabic", pronunciation: "ah-MEE-nah", letter: "A", popularity: 9, description: "Amina is a beloved classic associated with trust and safety. It carries a calm, reassuring quality that has endured across generations.", related: ["aaliyah", "maryam", "safiya"] },
  { slug: "maryam", name: "Maryam", arabic: "مَرْيَم", gender: "girl", meaning: "Beloved; a revered Quranic name", meaningTags: ["quranic", "devotion"], origin: "Arabic", pronunciation: "MAR-yam", letter: "M", popularity: 10, isQuranic: true, description: "Maryam is a deeply honoured Quranic name with a tender, familiar sound. It is an enduring choice for families seeking a name rich in faith and legacy.", related: ["amina", "safiya", "noor"] },
  { slug: "noor", name: "Noor", arabic: "نُور", gender: "unisex", meaning: "Light; illumination", meaningTags: ["light", "quranic"], origin: "Arabic", pronunciation: "NOOR", letter: "N", popularity: 10, isQuranic: true, description: "Noor is a luminous and versatile name with an immediate, elegant meaning. Its simplicity gives it rare strength across cultures and generations.", related: ["zara", "maryam", "lina"] },
  { slug: "zara", name: "Zara", arabic: "زَهْرَة", gender: "girl", meaning: "Flower; radiance; blossoming", meaningTags: ["flower", "beauty"], origin: "Arabic", pronunciation: "ZAH-rah", letter: "Z", popularity: 9, description: "Zara feels bright and elegant, with associations of flowers and radiance. It is a beautifully compact name with a lively finish.", related: ["noor", "aaliyah", "lina"] },
  { slug: "safiya", name: "Safiya", arabic: "صَفِيَّة", gender: "girl", meaning: "Pure; chosen friend", meaningTags: ["purity", "friendship"], origin: "Arabic", pronunciation: "sah-FEE-yah", letter: "S", popularity: 8, description: "Safiya is a refined name associated with purity and cherished friendship. It is traditional in feeling while remaining fresh and melodic.", related: ["amina", "aaliyah", "maryam"] },
  { slug: "lina", name: "Lina", arabic: "لِينَا", gender: "girl", meaning: "Tender; delicate palm tree", meaningTags: ["nature", "gentleness"], origin: "Arabic", pronunciation: "LEE-nah", letter: "L", popularity: 8, description: "Lina is a gentle, approachable name associated with tenderness and the natural world. Its soft sound makes it an effortless modern choice.", related: ["zara", "noor", "maya"] },
  { slug: "inaya", name: "Inaya", arabic: "عِنَايَة", gender: "girl", meaning: "Care; concern; protection", meaningTags: ["care", "protection"], origin: "Arabic", pronunciation: "ih-NAY-yah", letter: "I", popularity: 9, isUnique: true, description: "Inaya has become a much-loved contemporary choice for its gentle rhythm and its beautiful association with care and protection.", related: ["amina", "aaliyah", "lina"] },
  { slug: "maya", name: "Maya", arabic: "مَايا", gender: "girl", meaning: "Grace; princess", meaningTags: ["grace", "beauty"], origin: "Arabic", pronunciation: "MY-ah", letter: "M", popularity: 8, description: "Maya is a softly musical name found across several cultures. In this collection it is presented for its graceful, elegant association.", related: ["lina", "zara", "aaliyah"] },
  { slug: "hana", name: "Hana", arabic: "هَنَاء", gender: "girl", meaning: "Happiness; bliss", meaningTags: ["joy", "blessing"], origin: "Arabic", pronunciation: "HAH-nah", letter: "H", popularity: 7, isUnique: true, description: "Hana is light, classic, and joyful. Its association with happiness gives it a bright simplicity that remains quietly distinctive.", related: ["lina", "inaya", "maya"] },
  { slug: "layla", name: "Layla", arabic: "لَيْلَى", gender: "girl", meaning: "Night; dark beauty", meaningTags: ["night", "beauty"], origin: "Arabic", pronunciation: "LAY-lah", letter: "L", popularity: 8, description: "Layla is a lyrical classic whose poetic connection with night gives it a sense of depth, romance, and enduring appeal.", related: ["lina", "zara", "noor"] },
  { slug: "maryam-nur", name: "Maryam Nur", arabic: "مَرْيَم نُور", gender: "girl", meaning: "Maryam and light", meaningTags: ["light", "quranic"], origin: "Turkish", pronunciation: "MAR-yam NOOR", letter: "M", popularity: 6, isUnique: true, description: "Maryam Nur pairs a revered Quranic name with the radiant meaning of light, creating a distinctive two-part option for families.", related: ["maryam", "noor", "safiya"] },
  { slug: "arisha", name: "Arisha", arabic: "عَرِيشَة", gender: "girl", meaning: "Shelter; high place", meaningTags: ["protection", "elevation"], origin: "Arabic", pronunciation: "ah-REE-shah", letter: "A", popularity: 7, isUnique: true, description: "Arisha is an uncommon, elegant choice with a bright cadence and associations of shelter and a high place.", related: ["inaya", "aaliyah", "hana"] },
  { slug: "eiliyah", name: "Eiliyah", arabic: "إِيليَّة", gender: "girl", meaning: "Peaceful; close to God", meaningTags: ["peace", "faith"], origin: "Arabic", pronunciation: "ee-LEE-yah", letter: "E", popularity: 7, isUnique: true, description: "Eiliyah is a soft, contemporary choice that feels distinctive while keeping an elegant, spiritually resonant character.", related: ["aaliyah", "inaya", "lina"] },
  { slug: "ayla", name: "Ayla", arabic: "آيلا", gender: "girl", meaning: "Moonlight; halo around the moon", meaningTags: ["light", "nature"], origin: "Turkish", pronunciation: "EYE-lah", letter: "A", popularity: 8, description: "Ayla is a luminous choice with a smooth, modern sound. Its association with moonlight gives it a quietly poetic identity.", related: ["noor", "zara", "lina"] },
  { slug: "selim", name: "Selim", arabic: "سَلِيم", gender: "boy", meaning: "Safe; sound; peaceful", meaningTags: ["peace", "safety"], origin: "Turkish", pronunciation: "seh-LEEM", letter: "S", popularity: 7, description: "Selim is a distinguished classic with a serene meaning and gentle, polished cadence. It is widely appreciated across the Muslim world.", related: ["sami", "rizwan", "ihsan"] },
  { slug: "emir", name: "Emir", arabic: "أَمِير", gender: "boy", meaning: "Commander; prince", meaningTags: ["leadership", "strength"], origin: "Turkish", pronunciation: "eh-MEER", letter: "E", popularity: 8, description: "Emir is concise and assured, carrying an association with leadership and noble responsibility. Its international sound adds to its appeal.", related: ["zaid", "zayn", "sami"] },
  { slug: "dilara", name: "Dilara", arabic: "دِلَارَا", gender: "girl", meaning: "Adorning the heart; beloved", meaningTags: ["love", "beauty"], origin: "Persian", pronunciation: "dih-LAH-rah", letter: "D", popularity: 6, isUnique: true, description: "Dilara is a poetic Persian choice that combines an affectionate meaning with a graceful, flowing sound.", related: ["zara", "maya", "hana"] },
  { slug: "soraya", name: "Soraya", arabic: "ثُرَيَّا", gender: "girl", meaning: "The Pleiades; a cluster of stars", meaningTags: ["stars", "nature"], origin: "Persian", pronunciation: "so-RYE-yah", letter: "S", popularity: 7, isUnique: true, description: "Soraya has a celestial, timeless quality. Its association with a cluster of stars gives the name a distinct sense of wonder.", related: ["ayla", "noor", "zara"] },
  { slug: "faris", name: "Faris", arabic: "فَارِس", gender: "boy", meaning: "Knight; horseman", meaningTags: ["strength", "courage"], origin: "Arabic", pronunciation: "FAH-riss", letter: "F", popularity: 7, description: "Faris is a concise, traditional name with an association of courage and chivalry. It feels strong without being heavy.", related: ["emir", "zaid", "sami"] },
  { slug: "maheen", name: "Maheen", arabic: "مَاهِين", gender: "girl", meaning: "Like the moon; fine and delicate", meaningTags: ["moon", "beauty"], origin: "Urdu", pronunciation: "mah-HEEN", letter: "M", popularity: 6, isUnique: true, description: "Maheen is an elegant Urdu choice associated with moonlight and delicacy. It offers a rare balance of softness and presence.", related: ["ayla", "soraya", "noor"] },
];

export const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
export const origins = ["Arabic", "Persian", "Turkish", "Urdu"];
export const meaningTags = ["light", "blessing", "grace", "peace", "nature", "virtue", "beauty", "protection"];

export function getName(slug: string) {
  return names.find((entry) => entry.slug === slug);
}

export function getRelatedNames(record: NameRecord) {
  return record.related.map(getName).filter((item): item is NameRecord => Boolean(item));
}
