/** Quiet Courtyard homepage: an immersive editorial entrance that turns a name search into a meaningful path. */
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowRight, ChevronRight, Heart, Search, Sparkles, Star } from "lucide-react";
import { alphabet, names } from "@/lib/names";
import { useFavorites } from "@/hooks/useFavorites";
import { NameCard } from "@/components/NameCard";

const featured = [names.find((item) => item.slug === "ayaan")!, names.find((item) => item.slug === "maryam")!, names.find((item) => item.slug === "noor")!];
const meaningLinks = [
  { label: "Light", count: 12, href: "/meaning/light" }, { label: "Blessing", count: 8, href: "/meaning/blessing" }, { label: "Peace", count: 15, href: "/meaning/peace" }, { label: "Grace", count: 11, href: "/meaning/grace" }, { label: "Strength", count: 9, href: "/meaning/strength" }, { label: "Nature", count: 10, href: "/meaning/nature" },
];

export default function Home() {
  const [query, setQuery] = useState("");
  const { favorites, toggleFavorite } = useFavorites();
  const results = useMemo(() => query.trim() ? names.filter((record) => `${record.name} ${record.meaning}`.toLowerCase().includes(query.toLowerCase())).slice(0, 5) : [], [query]);
  return <main>
    <section className="relative isolate min-h-[650px] overflow-hidden bg-emerald-950 px-5 text-[#faf7f0] sm:px-8 lg:min-h-[720px] lg:px-12">
      <img src="/manus-storage/courtyard-hero_bf1011b6.jpg" alt="Sunlit stone courtyard with arches, olive tree, and a stone basin" className="absolute inset-0 -z-20 h-full w-full object-cover object-center" />
      <div className="absolute inset-0 -z-10 bg-gradient-to-r from-emerald-950 via-emerald-950/88 to-emerald-950/28" />
      <div className="absolute inset-x-0 bottom-0 h-40 bg-gradient-to-t from-emerald-950/65 to-transparent" />
      <div className="mx-auto flex min-h-[650px] max-w-[1440px] flex-col justify-between py-12 lg:min-h-[720px] lg:py-16">
        <div className="max-w-3xl pt-8 sm:pt-16 lg:pt-20"><p className="eyebrow mb-5 text-[#e7cf83]">Meaningful names, thoughtfully gathered</p><h1 className="max-w-2xl font-display text-5xl font-semibold leading-[0.92] tracking-[-0.07em] text-[#fffdf8] sm:text-6xl lg:text-8xl">Find the story<br />a name <em className="font-normal text-[#e7cf83]">begins.</em></h1><p className="mt-7 max-w-xl text-base leading-7 text-[#fffdf8]/78 sm:text-lg">Explore Muslim baby names through meaning, heritage, and the feeling you hope a name will carry.</p>
          <div className="relative mt-8 max-w-2xl"><div className="flex border border-white/20 bg-[#fffdf8] p-1.5 shadow-2xl"><div className="relative flex flex-1 items-center"><Search className="absolute left-4 h-5 w-5 text-emerald-950/45" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try a name, meaning, or letter..." className="w-full bg-transparent py-3 pl-12 pr-3 text-sm text-emerald-950 outline-none placeholder:text-emerald-950/45 sm:text-base" /></div><Link href={query ? `/search?q=${encodeURIComponent(query)}` : "/search"} className="inline-flex items-center gap-2 bg-[#c9a227] px-4 text-sm font-bold text-emerald-950 transition hover:bg-[#e0c05c] sm:px-6">Explore <ArrowRight className="h-4 w-4" /></Link></div>{results.length > 0 && <div className="absolute z-20 mt-2 w-full overflow-hidden border border-emerald-950/15 bg-[#fffdf8] shadow-xl"><p className="px-4 pt-3 text-[0.66rem] font-bold uppercase tracking-[0.16em] text-emerald-950/45">Matching names</p>{results.map((record) => <Link key={record.slug} href={`/name/${record.slug}`} className="flex items-center justify-between px-4 py-3 transition hover:bg-emerald-50"><div><span className="font-display text-lg text-emerald-950">{record.name}</span><span className="ml-3 text-sm text-emerald-950/55">{record.meaning}</span></div><ChevronRight className="h-4 w-4 text-[#0b6e4f]" /></Link>)}<Link href={`/search?q=${encodeURIComponent(query)}`} className="block border-t border-emerald-950/10 px-4 py-3 text-sm font-bold text-[#0b6e4f]">View all results</Link></div>}</div></div>
        <div className="flex flex-wrap items-end justify-between gap-6 border-t border-white/15 pt-6"><div className="flex gap-7"><div><p className="font-display text-2xl text-[#e7cf83]">2,000+</p><p className="mt-1 text-xs uppercase tracking-[0.15em] text-white/50">Names to grow into</p></div><div><p className="font-display text-2xl text-[#e7cf83]">18</p><p className="mt-1 text-xs uppercase tracking-[0.15em] text-white/50">Meanings to follow</p></div></div><p className="max-w-[18rem] text-right text-sm leading-5 text-white/60">No noise, no pressure—just a beautiful place to begin.</p></div>
      </div>
    </section>
    <section className="relative bg-[#f0ece1] px-5 py-12 sm:px-8 lg:px-12"><div className="absolute inset-0 bg-[url('/manus-storage/geometric-texture_fb886260.jpg')] bg-cover bg-center opacity-35" /><div className="relative mx-auto max-w-[1440px]"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow mb-2">Choose your first path</p><h2 className="font-display text-4xl font-semibold tracking-[-0.055em] text-emerald-950 sm:text-5xl">Begin with a letter.</h2></div><div className="flex gap-3"><Link href="/boy-names" className="text-sm font-semibold text-[#0b6e4f] underline underline-offset-4">Boy names</Link><span className="text-emerald-950/25">/</span><Link href="/girl-names" className="text-sm font-semibold text-[#0b6e4f] underline underline-offset-4">Girl names</Link></div></div><div className="grid grid-cols-6 gap-1.5 sm:grid-cols-9 md:grid-cols-13">{alphabet.map((letter) => <Link key={letter} href={`/girl-names/${letter.toLowerCase()}`} className="letter-index"><span>{letter}</span><small>{names.filter((name) => name.letter === letter).length || "–"}</small></Link>)}</div><p className="mt-5 text-xs leading-5 text-emerald-950/50">Every letter opens into a considered collection. Follow the one that already feels like a beginning.</p></div></section>
    <section className="mx-auto grid max-w-[1440px] gap-12 px-5 py-14 sm:px-8 lg:grid-cols-[0.9fr_1.1fr] lg:px-12 lg:py-20"><div className="relative min-h-[380px] overflow-hidden bg-emerald-950"><img src="/manus-storage/name-book_0944525b.jpg" alt="Open heritage journal with olive leaves and brass eight-point star paperweight" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-emerald-950/90 via-emerald-950/10 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7"><p className="eyebrow text-[#e7cf83]">Every name holds a world</p><p className="mt-3 max-w-sm font-display text-3xl leading-tight text-white">Discover the meaning that feels like your family.</p></div></div><div className="self-center"><p className="eyebrow mb-3">Browse by meaning</p><h2 className="font-display text-4xl font-semibold leading-[1] tracking-[-0.055em] text-emerald-950 sm:text-5xl">Start with the quality you hope to hold close.</h2><p className="mt-5 max-w-xl text-base leading-7 text-emerald-950/68">Light, gentleness, courage, grace—sometimes the meaning is the first thing a parent knows. Let it guide you into the collection.</p><div className="mt-7 grid gap-2 sm:grid-cols-2">{meaningLinks.map((item) => <Link key={item.label} href={item.href} className="group flex items-center justify-between border-b border-emerald-950/14 py-3 text-emerald-950 transition hover:border-[#0b6e4f] hover:text-[#0b6e4f]"><span className="font-display text-xl">{item.label}</span><span className="flex items-center gap-3 text-xs font-semibold text-emerald-950/45"><span>{item.count} names</span><ChevronRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></span></Link>)}</div></div></section>
    <section className="border-y border-emerald-950/10 bg-[#fffdf8] px-5 py-14 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1440px]"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow mb-2">Loved for a reason</p><h2 className="font-display text-4xl font-semibold tracking-[-0.055em] text-emerald-950 sm:text-5xl">Names to meet first.</h2></div><Link href="/search" className="inline-flex items-center gap-1 text-sm font-semibold text-[#0b6e4f] underline underline-offset-4">Explore the collection <ChevronRight className="h-4 w-4" /></Link></div><div className="grid gap-4 md:grid-cols-3">{featured.map((record) => <NameCard key={record.slug} record={record} isFavorite={favorites.includes(record.slug)} onToggle={toggleFavorite} />)}</div></div></section>
    <section className="mx-auto grid max-w-[1440px] gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[1.1fr_0.9fr] lg:px-12 lg:py-20"><div className="self-center"><p className="eyebrow mb-3">For families who value the full story</p><h2 className="font-display text-4xl font-semibold leading-[1.01] tracking-[-0.055em] text-emerald-950 sm:text-5xl">Made with care for a choice that matters.</h2><p className="mt-5 max-w-xl text-base leading-7 text-emerald-950/68">Each name brings together an accessible meaning, heritage, pronunciation guidance, and related options—so you can move from a first spark to a name you return to.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center bg-[#f0ece1] text-[#a57f1f]"><Star className="h-4 w-4" /></div><p className="text-sm leading-6 text-emerald-950/65"><strong className="block text-emerald-950">Thoughtful context</strong>Meaning, roots, and Arabic script in one place.</p></div><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center bg-[#f0ece1] text-[#a57f1f]"><Heart className="h-4 w-4" /></div><p className="text-sm leading-6 text-emerald-950/65"><strong className="block text-emerald-950">A private shortlist</strong>Save your favourites without an account.</p></div></div><Link href="/sources" className="mt-8 inline-flex items-center gap-2 border-b border-[#0b6e4f] pb-1 text-sm font-semibold text-[#0b6e4f]">How we approach names <ArrowRight className="h-4 w-4" /></Link></div><div className="relative aspect-square overflow-hidden bg-[#f0ece1] sm:aspect-[4/3]"><img src="/manus-storage/arabic-tiles_eac7a220.jpg" alt="Hand-glazed emerald and ivory eight-point star tilework" className="h-full w-full object-cover" /><div className="absolute inset-x-6 bottom-6 border border-white/45 bg-[#fffdf8]/90 p-5 backdrop-blur"><Sparkles className="h-5 w-5 text-[#a57f1f]" /><p className="mt-3 font-display text-2xl text-emerald-950">A name with roots.<br />A story in motion.</p></div></div></section>
  </main>;
}
