/** Quiet Courtyard trust pages: source clarity and editorial purpose are part of the discovery experience, not an afterthought. */
import { Link, useLocation } from "wouter";
import { ArrowRight, BadgeCheck, BookOpen, CheckCircle2, HeartHandshake, SearchCheck } from "lucide-react";
import { PageIntro } from "@/components/PageIntro";

const aboutBlocks = [
  { icon: SearchCheck, title: "Meaning before noise", copy: "The collection is designed around the questions families actually ask: what a name means, how it is pronounced, where it comes from, and what it might feel like to carry." },
  { icon: BookOpen, title: "Built for discovery", copy: "Browse by gender, letter, origin, or meaning. Each route is made to help you arrive at a smaller, more personal set of possibilities." },
  { icon: HeartHandshake, title: "Private by default", copy: "A shortlist is saved only in your browser. No signup, no social pressure, and no interruption to the moment of choosing." },
];
export default function InfoPage() {
  const [location] = useLocation();
  const isSources = location.startsWith("/sources");
  if (isSources) return <><PageIntro eyebrow="Editorial confidence" title="Sources & methodology" description="How we approach spelling, meaning, and context with care—and how to use this collection thoughtfully." trail={[{ label: "Sources & methodology" }]} /><main className="mx-auto max-w-4xl px-5 py-12 sm:px-8 lg:py-16"><div className="prose-courtyard"><p className="lead">Names travel across languages, regions, and family traditions. A single transliteration can have several valid spellings, and a name’s meaning may hold multiple shades of interpretation.</p><h2>Our editorial approach</h2><p>Each entry begins with commonly recognised Arabic, Persian, Turkish, Urdu, or associated linguistic roots. We then present a concise English meaning that aims for clarity, while avoiding the promise that a short gloss captures every cultural nuance.</p><h2>Arabic script & transliteration</h2><p>Arabic script is included wherever it supports recognition. Romanised spellings are provided as a practical guide and may vary by country, dialect, and a family’s own preference. When in doubt, consult a fluent speaker or a trusted regional source for pronunciation and spelling.</p><h2>Quranic and religious context</h2><p>Names marked Quranic are mentioned in, or have a longstanding and direct connection to, the Quranic tradition. This is a contextual label, not a judgement about any family’s choice. We encourage families seeking religious guidance to speak with a trusted scholar or community leader.</p><div className="method-callout"><BadgeCheck className="h-5 w-5" /><p><strong>Our commitment:</strong> we prefer useful context over inflated claims. This collection is a starting point for meaningful conversations, not a substitute for personal, linguistic, or religious advice.</p></div></div></main></>;
  return <><PageIntro eyebrow="The collection" title="A calmer way to find a name" description="Muslim Baby Names is an editorial discovery space for families looking for meaning, heritage, and a story that feels personal." trail={[{ label: "About" }]} /><main><section className="mx-auto grid max-w-[1440px] gap-10 px-5 py-12 sm:px-8 md:grid-cols-[0.8fr_1.2fr] lg:px-12 lg:py-16"><div className="relative overflow-hidden bg-emerald-950 p-8 text-[#faf7f0] sm:p-10"><div className="hero-pattern absolute inset-0 opacity-40" /><p className="relative eyebrow text-[#d9be70]">Our point of view</p><p className="relative mt-7 font-display text-3xl leading-[1.06] tracking-[-0.055em]">“A name is not a trend to chase. It is a beginning to sit with.”</p></div><div className="self-center"><p className="eyebrow mb-3">Designed for the moment that matters</p><h2 className="font-display text-4xl font-semibold leading-[1.02] tracking-[-0.05em] text-emerald-950">A thoughtful collection, not a noisy list.</h2><p className="mt-5 max-w-xl text-base leading-8 text-emerald-950/70">Finding a name often happens between conversations, hopes, and family stories. This experience was made to provide room for all of that—whether you begin with a familiar letter, a meaningful quality, or a name you heard once and cannot forget.</p><Link href="/sources" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#0b6e4f] underline underline-offset-4">Read our sources & methodology <ArrowRight className="h-4 w-4" /></Link></div></section><section className="border-y border-emerald-950/10 bg-[#f0ece1] px-5 py-12 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1440px]"><p className="eyebrow mb-3">What guides the site</p><div className="grid gap-px border border-emerald-950/10 bg-emerald-950/10 md:grid-cols-3">{aboutBlocks.map((block) => <div key={block.title} className="bg-[#f0ece1] p-7"><block.icon className="h-6 w-6 text-[#a57f1f]" /><h3 className="mt-5 font-display text-2xl text-emerald-950">{block.title}</h3><p className="mt-3 text-sm leading-6 text-emerald-950/65">{block.copy}</p></div>)}</div></div></section></main></>;
}
