/** Quiet Courtyard legal pages: direct, human-readable information that matches the website's actual behaviour. */
import { Link, useLocation } from "wouter";
import { ExternalLink, Mail, ShieldCheck } from "lucide-react";
import { PageIntro } from "@/components/PageIntro";

const updated = "25 August 2026";

function LegalLayout({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) {
  return <><PageIntro eyebrow={eyebrow} title={title} description={description} trail={[{ label: title }]} /><main className="mx-auto max-w-4xl px-5 py-12 sm:px-8 lg:py-16"><article className="prose-courtyard"><p className="lead">Last updated: {updated}</p>{children}</article></main></>;
}

function PrivacyPage() {
  return <LegalLayout eyebrow="Your information" title="Privacy policy" description="A clear account of what the site stores, what it does not collect, and how public discovery stays private by default."><p>Muslim Baby Names is an editorial name-discovery website. We design the public experience so you can explore names without creating an account or providing personal details.</p><h2>What we use</h2><div className="overflow-x-auto"><table><thead><tr><th>Category</th><th>Why it is used</th><th>Where it stays</th></tr></thead><tbody><tr><td>Shortlist and share preferences</td><td>To remember saved names, export-card choices, and locally visible share counts.</td><td>In your browser’s local storage or cache until you clear it.</td></tr><tr><td>Optional analytics</td><td>To understand aggregate visits and improve collection discovery, only after you choose to accept analytics.</td><td>Google Analytics and a local record of your accept or reject choice.</td></tr><tr><td>Technical information</td><td>To keep the website secure, reliable, and compatible with your browser.</td><td>Standard hosting, browser, and server logs.</td></tr><tr><td>Optional social sharing</td><td>To open a share action you specifically choose, such as a social platform or copied link.</td><td>The relevant third-party platform under its own privacy terms.</td></tr></tbody></table></div><h2>Analytics consent</h2><p>Analytics are disabled by default. The Google Analytics script is loaded only if you explicitly accept analytics in the cookie banner. If you reject analytics, the site stores that choice locally and does not load Google Analytics. You can change your choice at any time through the Cookie settings control at the lower left of the page; rejecting later also removes Google Analytics cookies that are accessible to this site.</p><h2>What we do not ask for</h2><p>The public name-discovery experience does not require a user account, payment information, a mailing address, or a child’s personal information. We do not sell personal information or use the shortlist as a marketing list.</p><h2>Third parties</h2><p>Your browser may interact with a third-party platform only when you deliberately accept analytics or use a share option. Those third parties operate under their own policies; please review them before using their services.</p><h2>Your choices</h2><p>You can clear locally stored shortlist, export, and consent preferences through your browser settings at any time. For a privacy question or request, contact us through the channel on the <Link href="/contact">Contact page</Link>.</p></LegalLayout>;
}

function TermsPage() {
  return <LegalLayout eyebrow="Using the collection" title="Terms of use" description="The shared expectations that keep Muslim Baby Names useful, respectful, and available for families."><h2>Using this website</h2><p>You may browse, save names locally, share links, and use the website’s name information for personal discovery. Please use the website lawfully and do not interfere with its security, availability, or other visitors’ access.</p><h2>Editorial information</h2><p>Name meanings, spellings, origins, phonetic guides, and related context are presented as an editorial starting point. Language, transliteration, regional custom, and family preference can all affect how a name is understood or used. The website is not a substitute for linguistic, cultural, religious, medical, legal, or professional advice.</p><h2>Content and intellectual property</h2><p>The website’s editorial copy, Quiet Courtyard visual system, code, graphics, and downloadable social-card layouts are protected by applicable law. You may share generated name cards for personal, non-misleading use. You may not reproduce the catalogue or automated outputs in bulk, misrepresent the service, or use the site to build a competing database without written permission.</p><h2>Links and third-party services</h2><p>External links and sharing actions are provided for convenience. We do not control third-party content, availability, advertising, or privacy practices. Your use of those services is governed by their own terms.</p><h2>Changes and availability</h2><p>We may update the website, these terms, or available features as the collection evolves. We aim for a reliable service but do not guarantee uninterrupted availability or error-free content. Continued use after a published change means you accept the updated terms.</p></LegalLayout>;
}

function ContactPage() {
  return <LegalLayout eyebrow="Get in touch" title="Contact" description="The right route for questions about the collection, your privacy, or a reported issue."><div className="method-callout"><Mail className="h-5 w-5" /><p><strong>Contact channel:</strong> Please send a direct message to the official <a href="https://in.pinterest.com/muslimbabynamesofficial/" target="_blank" rel="noreferrer">Muslim Baby Names Pinterest profile <ExternalLink className="inline h-3.5 w-3.5" /></a>. Include enough detail for us to understand your request and respond responsibly.</p></div><h2>What to include</h2><p>For a name-entry correction, include the relevant name and page link. For a privacy request, explain the browser or service you used and the nature of the request. For a site issue, include the public URL involved and any non-sensitive error message.</p><h2>Response scope</h2><p>We welcome constructive feedback and reports about broken pages, inaccessible content, or inaccurate presentation. We cannot provide individualized religious, legal, medical, or naming decisions, but we can explain the website’s editorial approach and data practices.</p></LegalLayout>;
}

function SafetyPage() {
  return <LegalLayout eyebrow="A respectful space" title="Child safety & community standards" description="How this family-focused discovery site approaches younger visitors, respectful content, and reporting."><div className="method-callout"><ShieldCheck className="h-5 w-5" /><p><strong>Family-focused by design:</strong> Muslim Baby Names is intended as a calm discovery resource for parents, families, and caregivers. It does not offer public profiles, direct messaging, user comments, or child-targeted social features.</p></div><h2>Children’s information</h2><p>We do not knowingly collect personal information from children through the public name-discovery experience. The site does not ask visitors to create an account, submit a child’s name, upload a photo, or post user-generated content.</p><h2>Respectful use</h2><p>We welcome families from many cultures, languages, and traditions. Content or conduct that is hateful, sexually exploitative, discriminatory, deceptive, violent, or intended to target a child is not permitted in any communication with us or use of our materials.</p><h2>Reporting a concern</h2><p>If you believe a page, link, social post, or interaction connected to this service raises a safety concern, contact us through the <Link href="/contact">Contact page</Link> and include the relevant public URL. If someone is in immediate danger, contact local emergency services or the appropriate child-safety authority in your area.</p><h2>Platform partners</h2><p>When we use a platform such as Pinterest to share editorial content, the platform’s own safety tools, reporting routes, and terms also apply. We will not use social publishing tools to solicit personal information from children or to create content directed at children without appropriate safeguards.</p></LegalLayout>;
}

export default function LegalPage() {
  const [location] = useLocation();
  if (location.startsWith("/terms")) return <TermsPage />;
  if (location.startsWith("/contact")) return <ContactPage />;
  if (location.startsWith("/child-safety")) return <SafetyPage />;
  return <PrivacyPage />;
}
